# Generated by Django 4.1 on 2022-12-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.URLField(default="", max_length=150),
        ),
    ]
