# Generated by Django 4.1 on 2023-01-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "experiences",
            "0003_alter_experience_category_alter_experience_host_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="experience_max_team",
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
