# Generated by Django 4.1 on 2023-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_experience_alter_booking_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="experience_max_team",
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
