# Generated by Django 4.1 on 2023-01-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_experience_max_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="experience_max_team",
        ),
    ]
